name: client_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  dropdown_button2: ^2.3.9
  get: ^4.6.6
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  get_storage: ^2.1.1
  otp_text_field_v2: ^1.0.3
  json_annotation: ^4.9.0
  flutter_stripe: ^11.4.0
  http: ^1.3.0
  dio: ^5.7.0
  firebase_auth: ^5.4.1
  flutter_stripe_web: ^6.4.0
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  flutter_test:
    sdk: flutter
  

 
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

 